# Generated by Django 3.1.2 on 2022-01-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='chargesFee',
            new_name='chargesFeee',
        ),
    ]
